### ISSUE TITLE
Get templates data from HTMLWebpackPlugin

### ISSUE THREAD

**Issue by ryuran** [jabney/render-template-loader#2]
Hello

Currently the only way to give data to template it `locals` option but I need access to HTMLWebpackPlugin `templateParameters` function output in my template.

Mainly because i use `svg-sprite-loader` and I need access to `htmlwebpackplugin.files.sprites`.
https://github.com/kisenka/svg-sprite-loader/tree/master/examples/interop-with-html-webpack-plugin

**Comment by jabney** [comment]
I'll look into a way to make plugins available in the loader options somewhere.

**Comment by ryuran** [comment]
I find a workaround using `svg-sprite-html-webpack` instead of `svg-sprite-loader`

**Comment by jabney** [comment]
Closed in favor of https://github.com/jabney/render-template-loader/issues/5
