### ISSUE TITLE
Make locals options able to be a function

### ISSUE THREAD

**Issue by ryuran** [jabney/render-template-loader#3]
`locals` option is a static object.
I need to fill data from a JSON file related to template file path.
I would have a function like it is in `twig-html-loader` https://github.com/radiocity/twig-html-loader#watch-data-from-files

**Comment by jabney** [comment]
Ok I'll see about allowing `locals` to be a function that returns an object.

**Comment by jabney** [comment]
Fixed in `1.1.0`

`options.locals` can new be an object or a function that returns an object:

https://github.com/jabney/render-template-loader/blob/master/test/loader.spec.js#L45-L65

**Comment by ryuran** [comment]
Good, but to be as good as `twig-html-loader` we need a way to add the json file as a dependency.

**Comment by jabney** [comment]
Closed and deferred to https://github.com/jabney/render-template-loader/issues/5
